language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # - cd project-3/udagram-apis/udagram-users
  - docker --version 
  - docker build -t udagram-user-restapi .
  - docker tag udagram-user-restapi "$DOCKER_USERNAME"/udagram-user-restapi:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-user-restapi